// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/[category]" | "/[locale]/about" | "/[locale]/admin/dashboard" | "/[locale]/admin/products" | "/[locale]/admin/products/create" | "/[locale]/admin/sales" | "/[locale]/cart" | "/[locale]/checkout" | "/[locale]/contact" | "/[locale]/customer/dashboard" | "/[locale]/dashboard" | "/[locale]/login" | "/[locale]/orders" | "/[locale]/products" | "/[locale]/products/[id]" | "/[locale]/register" | "/[locale]/reset_password" | "/[locale]/reviews" | "/[locale]/seller/dashboard" | "/[locale]/seller/products" | "/[locale]/seller/products/create" | "/[locale]/seller/sales" | "/[locale]/wishlist"
type AppRouteHandlerRoutes = "/api/adminLogin" | "/api/getCategorys" | "/api/products"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/[category]": { "locale": string; "category": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/admin/dashboard": { "locale": string; }
  "/[locale]/admin/products": { "locale": string; }
  "/[locale]/admin/products/create": { "locale": string; }
  "/[locale]/admin/sales": { "locale": string; }
  "/[locale]/cart": { "locale": string; }
  "/[locale]/checkout": { "locale": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/customer/dashboard": { "locale": string; }
  "/[locale]/dashboard": { "locale": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/orders": { "locale": string; }
  "/[locale]/products": { "locale": string; }
  "/[locale]/products/[id]": { "locale": string; "id": string; }
  "/[locale]/register": { "locale": string; }
  "/[locale]/reset_password": { "locale": string; }
  "/[locale]/reviews": { "locale": string; }
  "/[locale]/seller/dashboard": { "locale": string; }
  "/[locale]/seller/products": { "locale": string; }
  "/[locale]/seller/products/create": { "locale": string; }
  "/[locale]/seller/sales": { "locale": string; }
  "/[locale]/wishlist": { "locale": string; }
  "/api/adminLogin": {}
  "/api/getCategorys": {}
  "/api/products": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
